services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    restart: always
    volumes:
      - ./static:/app/static
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: darts.app
    command: gunicorn --bind 0.0.0.0:5000 --timeout 100 darts.app:app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./static:/static